USE EMPRESA;

INSERT INTO clientes SELECT 
DNI,NOMBRE,DIRECCION_1 AS DIRECCION,BARRIO,CIUDAD,ESTADO,CP,FECHA_DE_NACIMIENTO AS FECHA_NACIMIENTO,
EDAD,SEXO, LIMITE_DE_CREDITO AS LIMITE_CREDITO, VOLUMEN_DE_COMPRA AS VOLUMEN_COMPRA, PRIMERA_COMPRA
FROM JUGOS_VENTAS.TABLA_DE_CLIENTES;

INSERT INTO vendedores SELECT 
MATRICULA, NOMBRE, BARRIO, PORCENTAJE_COMISION AS COMISION, FECHA_ADMISION, VACACIONES
FROM jugos_ventas.tabla_de_vendedores;

INSERT INTO productos SELECT 
CODIGO_DEL_PRODUCTO AS CODIGO, NOMBRE_DEL_PRODUCTO AS DESCRIPCION, SABOR, TAMANO, ENVASE, PRECIO_DE_LISTA AS PRECIO
FROM jugos_ventas.TABLA_DE_PRODUCTOS;

INSERT INTO facturas
SELECT NUMERO, FECHA_VENTA AS FECHA, DNI, MATRICULA, IMPUESTO
FROM jugos_ventas.facturas WHERE DNI IN (SELECT DNI FROM CLIENTES);

INSERT INTO items SELECT DISTINCT
NUMERO, CODIGO_DEL_PRODUCTO AS CODIGO, CANTIDAD, PRECIO
FROM jugos_ventas.items_facturas WHERE NUMERO IN (SELECT NUMERO FROM FACTURAS);

